# Generated by Django 2.1.5 on 2021-07-28 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_category_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
