# Generated by Django 2.1.5 on 2021-08-04 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0007_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='views',
            new_name='likes',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='views',
            new_name='likes',
        ),
    ]
