# Generated by Django 2.1.5 on 2021-08-04 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0008_auto_20210804_1521'),
    ]

    operations = [
    ]
